commit:
  auto_message: true
  auto_push: false
  max_files_per_commit: 50
  message_template: '{type}: {description}'
global:
  auto_save: true
  log_level: INFO
  max_log_files: 10
monitoring:
  debounce_seconds: 5.0
  enabled: true
  ignore_patterns:
  - '*.log'
  - '*.tmp'
  - '*.pyc'
  - node_modules/
  - .git/
  - __pycache__/
  - .vscode/
  - .idea/
  - '*.swp'
  - '*.swo'
  - .DS_Store
  - Thumbs.db
repositories: []
schedule:
  enabled: false
  mode: daily
  time: '18:00'
